name: auto merge pull requests

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ledgerhq-shared-small
    timeout-minutes: 60
    steps:

      - name: Automatically merge pull requests
        timeout-minutes: 60
        uses: gsoc2/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: "${{ secrets.CI_BOT_TOKEN }}"
          MERGE_LABELS: automerge
          MERGE_METHOD: squash
          MERGE_FILTER_AUTHOR: '^(dependabot|renovate|ldg-github-ci)$'
          MERGE_FORKS: false
          MERGE_RETRIES: 120
          MERGE_RETRY_SLEEP: 30
          MERGE_DELETE_BRANCH: true
          BASE_BRANCHES: 'next'
